name:                bancoringa
version:             0.1.0.0
github:              "githubuser/bancoringa"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/bancoringa#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  bancoringa-exe:
    main:                Atividade02.hs
    source-dirs:         src
    ghc-options:
    - -O2 -Wall
    - -main-is Atividade02
    dependencies:
    - bancoringa

tests:
  bancoringa-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -O2 -Wall
    dependencies:
    - bancoringa
    - tasty
    - tasty-hunit
