name:                atividade1-unitario-app
version:             0.1.0.0
github:              "githubuser/atividade1-unitario-app"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/atividade1-unitario-app#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  atividade1-unitario-app-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - atividade1-unitario-app

tests:
  atividade1-unitario-app-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - atividade1-unitario-app
    - tasty
    - tasty-hunit
